// Code generated by protoc-gen-gmsec. DO NOT EDIT.

package test

// Tool descriptions from proto comments
const (
	// 测试函数
	Service_Tfunc_ToolDesc = "测试函数"
	// 测试函数
	Service2_Tfunc_ToolDesc = "测试函数"
)
