// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package test

import (
	context "context"
	micro "github.com/gmsec/micro"
	client "github.com/gmsec/micro/client"
	server "github.com/gmsec/micro/server"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface
var _ server.Server
var _ client.Client
var _ micro.Service

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TServiceClient is the client API for TService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TServiceClient interface {
	// Tfunc 测试函数
	Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	// 测试函数2
	Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type tServiceClient struct {
	cc client.Client
}

// GetTServiceName get client name(package.class)
func GetTServiceName() string {
	return "test.TService"
}

// GetTServiceClient get client by clientname
func GetTServiceClient() TServiceClient {
	cc := micro.GetClient(GetTServiceName())
	return &tServiceClient{cc}
}

// GetTServiceClientByName get client by custom name
func GetTServiceClientByName(name string) TServiceClient {
	cc := micro.GetClient(name)
	return &tServiceClient{cc}
}

func NewTServiceClient(cc client.Client) TServiceClient {
	return &tServiceClient{cc}
}

func (c *tServiceClient) Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.TService/Tfunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tServiceClient) Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.TService/Tfunc2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TServiceServer is the server API for TService service.
type TServiceServer interface {
	// Tfunc 测试函数
	Tfunc(context.Context, *User) (*User, error)
	// 测试函数2
	Tfunc2(context.Context, *User) (*User, error)
}

// UnimplementedTServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTServiceServer struct {
}

func (*UnimplementedTServiceServer) Tfunc(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc not implemented")
}
func (*UnimplementedTServiceServer) Tfunc2(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc2 not implemented")
}

func RegisterTServiceServer(s server.Server, srv TServiceServer) {
	s.GetServer().RegisterService(&_TService_serviceDesc, srv)
}

func _TService_Tfunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TServiceServer).Tfunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TService/Tfunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TServiceServer).Tfunc(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _TService_Tfunc2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TServiceServer).Tfunc2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TService/Tfunc2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TServiceServer).Tfunc2(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _TService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.TService",
	HandlerType: (*TServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tfunc",
			Handler:    _TService_Tfunc_Handler,
		},
		{
			MethodName: "Tfunc2",
			Handler:    _TService_Tfunc2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

// TService2Client is the client API for TService2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TService2Client interface {
	// Tfunc 测试函数
	Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	// 测试函数2
	Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type tService2Client struct {
	cc client.Client
}

// GetTService2Name get client name(package.class)
func GetTService2Name() string {
	return "test.TService2"
}

// GetTService2Client get client by clientname
func GetTService2Client() TService2Client {
	cc := micro.GetClient(GetTService2Name())
	return &tService2Client{cc}
}

// GetTService2ClientByName get client by custom name
func GetTService2ClientByName(name string) TService2Client {
	cc := micro.GetClient(name)
	return &tService2Client{cc}
}

func NewTService2Client(cc client.Client) TService2Client {
	return &tService2Client{cc}
}

func (c *tService2Client) Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.TService2/Tfunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tService2Client) Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.TService2/Tfunc2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TService2Server is the server API for TService2 service.
type TService2Server interface {
	// Tfunc 测试函数
	Tfunc(context.Context, *User) (*User, error)
	// 测试函数2
	Tfunc2(context.Context, *User) (*User, error)
}

// UnimplementedTService2Server can be embedded to have forward compatible implementations.
type UnimplementedTService2Server struct {
}

func (*UnimplementedTService2Server) Tfunc(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc not implemented")
}
func (*UnimplementedTService2Server) Tfunc2(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc2 not implemented")
}

func RegisterTService2Server(s server.Server, srv TService2Server) {
	s.GetServer().RegisterService(&_TService2_serviceDesc, srv)
}

func _TService2_Tfunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TService2Server).Tfunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TService2/Tfunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TService2Server).Tfunc(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _TService2_Tfunc2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TService2Server).Tfunc2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TService2/Tfunc2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TService2Server).Tfunc2(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _TService2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.TService2",
	HandlerType: (*TService2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tfunc",
			Handler:    _TService2_Tfunc_Handler,
		},
		{
			MethodName: "Tfunc2",
			Handler:    _TService2_Tfunc2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
