// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package test

import (
	context "context"
	micro "github.com/gmsec/micro"
	client "github.com/gmsec/micro/client"
	server "github.com/gmsec/micro/server"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface
var _ server.Server
var _ client.Client
var _ micro.Service

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	// Tfunc 测试函数
	Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	// 测试函数2
	Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type serviceClient struct {
	cc client.Client
}

// GetServiceName get client name(package.class)
func GetServiceName() string {
	return "test.service"
}

// GetServiceClient get client by clientname
func GetServiceClient() ServiceClient {
	cc := micro.GetClient(GetServiceName())
	return &serviceClient{cc}
}

// GetServiceClientByName get client by custom name
func GetServiceClientByName(name string) ServiceClient {
	cc := micro.GetClient(name)
	return &serviceClient{cc}
}

func NewServiceClient(cc client.Client) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.service/Tfunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.service/Tfunc2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	// Tfunc 测试函数
	Tfunc(context.Context, *User) (*User, error)
	// 测试函数2
	Tfunc2(context.Context, *User) (*User, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Tfunc(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc not implemented")
}
func (*UnimplementedServiceServer) Tfunc2(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc2 not implemented")
}

func RegisterServiceServer(s server.Server, srv ServiceServer) {
	s.GetServer().RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Tfunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Tfunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.service/Tfunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Tfunc(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Tfunc2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Tfunc2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.service/Tfunc2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Tfunc2(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tfunc",
			Handler:    _Service_Tfunc_Handler,
		},
		{
			MethodName: "Tfunc2",
			Handler:    _Service_Tfunc2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

// Service2Client is the client API for Service2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Service2Client interface {
	// Tfunc 测试函数
	Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	// 测试函数2
	Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type service2Client struct {
	cc client.Client
}

// GetService2Name get client name(package.class)
func GetService2Name() string {
	return "test.service2"
}

// GetService2Client get client by clientname
func GetService2Client() Service2Client {
	cc := micro.GetClient(GetService2Name())
	return &service2Client{cc}
}

// GetService2ClientByName get client by custom name
func GetService2ClientByName(name string) Service2Client {
	cc := micro.GetClient(name)
	return &service2Client{cc}
}

func NewService2Client(cc client.Client) Service2Client {
	return &service2Client{cc}
}

func (c *service2Client) Tfunc(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.service2/Tfunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service2Client) Tfunc2(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	conn, err := c.cc.Next()
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	out := new(User)
	err = conn.Invoke(ctx, "/test.service2/Tfunc2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Service2Server is the server API for Service2 service.
type Service2Server interface {
	// Tfunc 测试函数
	Tfunc(context.Context, *User) (*User, error)
	// 测试函数2
	Tfunc2(context.Context, *User) (*User, error)
}

// UnimplementedService2Server can be embedded to have forward compatible implementations.
type UnimplementedService2Server struct {
}

func (*UnimplementedService2Server) Tfunc(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc not implemented")
}
func (*UnimplementedService2Server) Tfunc2(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tfunc2 not implemented")
}

func RegisterService2Server(s server.Server, srv Service2Server) {
	s.GetServer().RegisterService(&_Service2_serviceDesc, srv)
}

func _Service2_Tfunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Service2Server).Tfunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.service2/Tfunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Service2Server).Tfunc(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service2_Tfunc2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Service2Server).Tfunc2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.service2/Tfunc2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Service2Server).Tfunc2(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.service2",
	HandlerType: (*Service2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tfunc",
			Handler:    _Service2_Tfunc_Handler,
		},
		{
			MethodName: "Tfunc2",
			Handler:    _Service2_Tfunc2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
