// Code generated by protoc-gen-gmsec. DO NOT EDIT.

package test

// Tool descriptions from proto comments
const (
	// 测试函数
	TService_Tfunc_ToolDesc = "测试函数"
	// 测试函数
	TService2_Tfunc_ToolDesc = "测试函数"
)
