package plugin

import (
	"strconv"
	"strings"

	gengo "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"
	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateFile generates a .pb.go file containing Go structs with jsonschema_description tags
func GenerateFile(gen *protogen.Plugin, file *protogen.File) error {
	// 调用gengo.GenerateFile生成基础代码
	gengo.GenerateFile(gen, file)
	// 生成常量配置文件
	generateConstantFile(gen, file)
	return nil
}

// generateConstantFile generates a constants file containing tool descriptions from service method comments
func generateConstantFile(gen *protogen.Plugin, file *protogen.File) {
	// 检查是否有service
	if len(file.Services) == 0 {
		return
	}

	// 收集符合条件的方法
	var constantEntries []struct {
		serviceName string
		methodName  string
		desc        string
	}

	for _, service := range file.Services {
		for _, method := range service.Methods {
			comment := strings.TrimSpace(string(method.Comments.Leading))
			if comment == "" {
				continue
			}
			// 移除注释前缀//
			comment = strings.TrimSpace(strings.TrimPrefix(comment, "//"))
			// 检查注释格式：是否以方法名开头
			if strings.HasPrefix(comment, method.GoName+" ") {
				// 提取描述部分
				desc := strings.TrimSpace(strings.TrimPrefix(comment, method.GoName+" "))
				constantEntries = append(constantEntries, struct {
					serviceName string
					methodName  string
					desc        string
				}{serviceName: service.GoName, methodName: method.GoName, desc: desc})
			}
		}
	}

	// 如果没有符合条件的方法，不生成文件
	if len(constantEntries) == 0 {
		return
	}

	// 生成常量文件
	filename := file.GeneratedFilenamePrefix + ".pb.constants.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-gmsec. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("// Tool descriptions from proto comments")
	g.P("const (")

	for _, entry := range constantEntries {
		g.P("\t// ", entry.desc)
		// 生成常量名：ServiceName_MethodName_ToolDesc，使用下划线区分
		constantName := entry.serviceName + "_" + entry.methodName + "_ToolDesc"
		g.P("\t", constantName, " = ", strconv.Quote(entry.desc))
	}

	g.P(")")
}
